### ISSUE TITLE
Use readAsArrayBuffer for image uploads

### ISSUE THREAD

**Issue by mjumbewu** [openplans/shareabouts#11]
Use [readAsArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/API/FileReader#readAsArrayBuffer%28%29) instead of [readAsBinaryString](https://github.com/openplans/shareabouts/blob/master/src/sa_web/static/js/utils.js#L150) for image uploads, as otherwise reasonable versions of IE do not support readAsBinaryString.

**Comment by cloudlakecho** [comment]
What do you need to close this issue?

**Comment by BenSturmfels** [comment]
Closing - this was fixed in 1bdf2fb6cc1bda81e41d6f3ce71649d5bea680c9 November 2013
