### ISSUE TITLE
CSRF error when immediately commenting on submitted place.

### ISSUE THREAD

**Issue by tmeasday** [openplans/shareabouts#135]
Reproduction:
1. Submit a place.
2. Close the submission success page.
3. Open the place.
4. Write a comment.

Result:
![screen shot 2014-08-20 at 1 51 38 pm](https://cloud.githubusercontent.com/assets/132554/3976433/f3ad1ca4-2821-11e4-87a3-08a5156942db.png)

I think the issue is that the form is actually submitting, because the survey-view didn't initialize for some reason.

Reproduced with 3.15.6

**Comment by BenSturmfels** [comment]
Suggest closing this issue - no indication that this is a systemic issue or that the problem persisted.
