### ISSUE TITLE
Points snapping to geocoded locations

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts#156]
I place a point on the map, when clicking save, the point moves slightly. I think the point is getting snapped to a geocoded location, because the issue doesn't happen when I turn off geocoding in my config.yml.

Running the latest Shareabouts, deployed here - http://suggest.bayareabikeshare.com/13/37.74160/-122.45327

**Comment by BenSturmfels** [comment]
This no longer appears to be an issue - I can't reproduce, so closing.
