### ISSUE TITLE
Support new Mapbox GL tiles

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts#159]
Previous Shareabouts maps have successfully used raster tiles generated in Tilemill. Unfortunately, Tilemill is deprecated by Mapbox in favor of their web-based Studio. Studio doesn't export old-style map tiles. Could Shareabouts use new GL tiles instead?

**Comment by mjumbewu** [comment]
This is possible as of commit e5aab94. There is a note about it in [the config docs](https://github.com/openplans/shareabouts/blob/master/doc/CONFIG.md#base-layer-options), and an example [in the default config](https://github.com/openplans/shareabouts/blob/fd01af07063d61641036cef53e642d82e146ba9e/src/flavors/defaultflavor/config.yml#L37).
