### ISSUE TITLE
Maps with Mapbox GL won't work in Safari 7.1 or Firefox

### ISSUE THREAD

**Issue by fkh** [openplans/shareabouts#162]
Mapbox GL requires WebGL, not fully supported in Safari 7.1 or any Firefox version (see http://caniuse.com/#feat=webgl).

Maybe maps with Mapbox GL require some different isSupported settings in utils.js?

**Comment by andycochran** [comment]
Isn't Mapbox GL specifically for iOS? 
Maybe Shareabouts + Mapbox GL should be it's own client.

**Comment by fkh** [comment]
Or we could use a "get a better browser" message? If you use a Mapbox GL layer, the map half-loads and there are console errors.

(Mapbox GL is awesome though)
