### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by TownofMiamiLakes** [openplans/shareabouts#184]
No able to Sign-In Via Twitter https://shareaboutsapi.poepublic.com/api/v2/users/login/twitter/

Server Error (500)

**Comment by mjumbewu** [comment]
Hi there,

This is a known issue with the Twitter integration, and we are working with Twitter's developer support to get it resolved. Will post back here when we have more information.

**Comment by TownofMiamiLakes** [comment]
This issue is tied to a public grant opportunity with a deadline and needs to be resolved asap.
